name: Build and Release JAR

on:
  push:
    tags:
      - "v*" # Trigger on tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Build JAR file
      - name: Build JAR with Maven
        run: mvn clean package

      # Archive the JAR as an artifact
      - name: Save JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-tracker-jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout code (needed to access the repository)
      - name: Checkout code
        uses: actions/checkout@v3

      # Download the JAR artifact from the build job
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: task-tracker-jar

      - name: List files in target folder
        run: ls -l /home/runner/work/Task-Tracker-Java/Task-Tracker-Java

      # Create Release on GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TASK_TRACKER_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload the JAR to GitHub Releases
      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TASK_TRACKER_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/Task-Tracker-Java/Task-Tracker-Java/tasktracker-${{ github.ref_name }}.jar # Adjust this if needed based on your artifact naming.
          asset_name: tasktracker-${{ github.ref_name }}.jar # Ensure this matches your expected naming convention.
          asset_content_type: application/java-archive
